### ISSUE TITLE
CAN transceiver

### ISSUE THREAD

**Issue by NicoEFI** [pierremolinaro/acan-stm32#2]
Hello Pierre
Which CAN transceiver IC is better to use with an NucleoL432KC? MCP2551?

**Comment by pierremolinaro** [comment]
Hello,

I do not recommend using the MCP2551 with a microcontroller powered at 3.3 V. If it's not 5V-tolerant, you could damage it.

I usually use an MCP2562. Connect the Vio pin to 3.3V for a 3.3V microcontroller (as the STM32L432KC), to 5V for a 5V microcontroller (as the Arduino Uno). Always connect the VDD pin to 5V. Connect the STBY pin to GND, unless you use the sandby mode.

Pierre
