### ISSUE TITLE
geneneric STM32F303K8T6 

### ISSUE THREAD

**Issue by NicoEFI** [pierremolinaro/acan-stm32#3]
Hello Pierre
I built my own custom board with an STM32F303K8T6 with an integrated CAN transceiver (MCP2562).
I would like to use your library but I get an error if I use the generic STM32F303K8 board from STM32DUINO.
d:\Users\Ronan\Documents\Arduino\libraries\ACAN_STM32\src/ACAN_STM32_Settings.h:14:4: error: #error "Unhandled Nucleo Board"
    14 | #error "Unhandled Nucleo Board"

Could you include this board please?

![image](https://github.com/pierremolinaro/acan-stm32/assets/23416971/f81ddba9-4bea-4474-9139-4ab056918f4c)
![image](https://github.com/pierremolinaro/acan-stm32/assets/23416971/89af6951-06f7-4c1c-9620-ddd9a514a140)

**Comment by pierremolinaro** [comment]
Nice board!

I have added the generic STM32F303K8 board, tested compilation with the "Generic F303K8Tx" setiing. I have updated the repository:
	https://github.com/pierremolinaro/acan-stm32

However, I cannot test the can clock frequency. I use the result of HAL_RCC_GetPCLK1Freq function as can clock frequency, it is advisable to check that the bit rate is correct.

If it is ok, I will make a release.

Pierre

**Comment by NicoEFI** [comment]
Thank you Pierre
It seems to work
 (LoopBackDemo) 
![image](https://github.com/pierremolinaro/acan-stm32/assets/23416971/a1bc4ee6-022d-4bfb-bb51-8688bd542ea6)

(LoopBackDemoIntensive)
![image](https://github.com/pierremolinaro/acan-stm32/assets/23416971/133cf250-b29c-466f-9bdd-f1f17372863d)

**Comment by NicoEFI** [comment]
Thank you Pierre
It seems to work
(LoopBackDemoIntensive)
![image](https://github.com/pierremolinaro/acan-stm32/assets/23416971/a918adf3-6d2e-498f-a66e-ea03941d9c79)
